# Generated by Django 3.2.5 on 2021-11-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datatext',
            fields=[
                ('Id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Content', models.TextField(default='', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('Criminals', models.CharField(default='', max_length=5, primary_key=True, serialize=False)),
                ('Gender', models.CharField(default='', max_length=2)),
                ('Ethnicity', models.CharField(default='', max_length=5)),
                ('Birthplace', models.CharField(default='', max_length=100)),
                ('Accusation', models.CharField(default='', max_length=20)),
                ('Courts', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
