# Generated by Django 3.2.5 on 2021-11-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_tempsave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatext',
            name='Content',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='tempsave',
            name='Content',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
