# Generated by Django 3.2.5 on 2021-11-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0004_alter_information_accusation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='Criminals',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
