# Generated by Django 3.2.5 on 2021-11-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0005_alter_information_criminals'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatext',
            name='Criminals',
            field=models.CharField(default='空', max_length=50),
        ),
        migrations.AddField(
            model_name='datatext',
            name='Keywords',
            field=models.CharField(default='空', max_length=50),
        ),
        migrations.AddField(
            model_name='datatext',
            name='OverTime',
            field=models.CharField(default='2099-12-31', max_length=15),
        ),
        migrations.AddField(
            model_name='datatext',
            name='StartTime',
            field=models.CharField(default='1900-01-01', max_length=15),
        ),
    ]
