# Generated by Django 3.2.5 on 2021-11-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0006_auto_20211130_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatext',
            name='Page',
            field=models.IntegerField(default=0),
        ),
    ]
