# Generated by Django 3.2.5 on 2022-01-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0007_datatext_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatext',
            name='Id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
