# Generated by Django 3.2.5 on 2022-01-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0008_alter_datatext_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatext',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
