# Generated by Django 3.2.5 on 2022-01-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0009_alter_datatext_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatext',
            name='Unique',
            field=models.CharField(default='', max_length=1000, unique=True),
        ),
    ]
