# Generated by Django 3.2.5 on 2022-01-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0011_datatext_courts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatext',
            name='Content',
            field=models.TextField(default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='tempsave',
            name='Content',
            field=models.TextField(default='', max_length=20000),
        ),
    ]
